name: CD - DAST

on:
  workflow_dispatch:   # Executa manualmente
  push:
    branches: [ "main" ]

jobs:
  security-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build da solução
        run: dotnet build Sprint3-CSHARP/Sprint.sln --no-restore

      - name: Rodar API em background
        run: dotnet run --project Sprint3-CSHARP/CandidatosApi/SprintApi.csproj &
      
      - name: Aguardar API iniciar
        run: sleep 15

      - name: Rodar OWASP ZAP
        run: |
          docker run --rm -v $(pwd)/docs:/zap/wrk/:rw \
            owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:5000 \
            -r zap-report.html
        working-directory: .

      - name: Upload Relatório DAST
        uses: actions/upload-artifact@v3
        with:
          name: dast-report
          path: docs/zap-report.html