name: CD - DAST

on:
  workflow_dispatch: # Manual trigger - Executar manualmente na aba do Github "Actions"
  push:
    branches: [ "main" ]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print working dir and tree
        run: |
          pwd
          ls -la
          echo "----"
          ls -la Sprint3-CSHARP || true

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore Sprint3-CSHARP/Sprint.sln

      - name: Build API
        run: dotnet build Sprint3-CSHARP/CandidatosApi/SprintApi.csproj

      - name: Run API in background
        run: dotnet run --project Sprint3-CSHARP/CandidatosApi/SprintApi.csproj --urls "http://0.0.0.0:5000" --no-build &
      
      - name: Wait for 200 on /
        run: |
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:5000/ >/dev/null; then
              echo "API is up"
              break
            fi
            sleep 2
          done
          
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker pull zaproxy/zap-stable
          chmod 777 docs   # garante permissão para o container criar o relatório
          docker pull zaproxy/zap-stable
          docker run --rm -v $(pwd)/docs:/zap/wrk/:rw zaproxy/zap-stable zap-baseline.py \
            -t http://127.0.0.1:5000 \
            -r zap-report.html

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: docs/zap-report.html
          if-no-files-found: error
          retention-days: 7