name: CD - DAST Scan

on:
  push:
    branches: [ main ]

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Build & Publish
        run: dotnet publish src/MyApp.csproj -c Release -o ./publish

      - name: Run app in background
        run: |
          nohup dotnet ./publish/MyApp.dll --urls "http://localhost:5000" & echo $! > app.pid

      - name: Wait for app
        run: |
          for i in {1..30}; do curl -sSf http://localhost:5000 && break || sleep 2; done

      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm -v "$(pwd)":/zap/wrk:rw -t owasp/zap2docker-stable zap-baseline.py \
            -t http://host.docker.internal:5000 -r zap-report.html || true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html