name: CI - SAST + SCA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build da solução
        run: dotnet build Sprint3-CSHARP/Sprint.sln --no-restore

      # ------------------------
      # SAST - Semgrep
      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Rodar análise SAST
        run: |
          semgrep --config auto \
                  --config ./ci/semgrep-rules/custom-rule.yml \
                  Sprint3-CSHARP/ \
                  --json > docs/sast-report.json

      # ------------------------
      # SCA - Dependency Check
      - name: Instalar Dependency-Check
        run: |
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.2/dependency-check-10.0.2-release.zip -o depcheck.zip
          unzip depcheck.zip -d depcheck

      - name: Rodar análise SCA
        run: |
          ./depcheck/dependency-check/bin/dependency-check.sh \
            --project "Sprint3-CSHARP" \
            --scan Sprint3-CSHARP/ \
            --format "HTML" \
            --out docs/sca-report.html

      - name: Upload Relatórios (artefatos)
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: docs/