name: CI - SAST + SCA

on: [push, pull_request]

jobs:
  sast-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=p/security --json --output semgrep-report.json ./src || true

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Check vulnerable NuGet packages
        run: dotnet list src/MyApp.csproj package --vulnerable --include-transitive > dotnet-vuln.txt || true

      - name: Upload NuGet vuln report
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-vuln
          path: dotnet-vuln.txt

      - name: Run OWASP Dependency-Check
        run: |
          docker run --rm -v "$(pwd)":/src owasp/dependency-check:latest \
            --project "MyApp" --scan /src --format HTML --out /src/ci/dependency-check

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ci/dependency-check